version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      typescript-eslint:
        patterns:
          - '@typescript-eslint/*'
      vitest:
        patterns:
          - 'vitest'
          - '@vitest/*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
